### PR TITLE
Fix container build: build svm-rs in upstream rust layer

### PR DESCRIPTION
**Pull request by dbast**
A new svm-rs version was released yesterday, which breaks the container build see:
* https://github.com/alloy-rs/svm-rs/tags 
* https://app.circleci.com/pipelines/github/Consensys/mythril/1128/workflows/6ea1da95-5ed5-4154-ab56-04b4916baa6f/jobs/7061

This PR fixes the svm-rs build by building in upstream rust container, which has a more complete rust tooling setup and does not run into the ```error: linking with `cc` failed``` issue.

Also removes some build layers not needed anymore.

### CODE REVIEW

**Comment by dbast** [comment]
The container build is green again after the recent PR merges. Maybe this PR is not required.

**Comment by norhh** [comment]
This happens due to issues with emulating some arm builds on x86 or emulating some x86 builds on arm (It is a bit tedious to perform multiplatform builds on multiple platforms and combine them). So, it crashes once in a while. Will work when restarted.

**Comment by dbast** [comment]
There was definitely something else as I could reproduce the issue multiple times locally even when building without multiarch emulation... maybe this resolved via some changes in the rustup installer... anyways, it resolved thus closing this PR

**Comment by norhh** [comment]
Isn't it still useful even without the issue?

**Review by norhh — APPROVED** [review]

**Pull request merged**
