### PR TITLE
Run black + ruff via pre-commit, fix findings to reduce requirements.txt

### PR DESCRIPTION
**Pull request by dbast**
This contains 7 commits, where automatic and manual changes are precisely separated (can split those into multiple PRs if thats desired):
* https://github.com/Consensys/mythril/commit/11b1afc05e6f2ad414ef4f2566bb56a0af8455e4 Enables running black via pre-commit + Github workflow and updates the black version (no mythril code changes)
* https://github.com/Consensys/mythril/commit/c7d0edab8cbc2128111dce70484187baa392a4c9 Applies black via pre-commit (fully automatic, no manual code changes)
* https://github.com/Consensys/mythril/commit/aa0b097ee1a080295fdc51da7480d2ec6231c782 Enables also running ruff via the ruleset "F" (no mythril code changes) ... "F" = pyflakes (also part of flake8) finds e.g. unused imports, assigned by unused variables etc.
* https://github.com/Consensys/mythril/commit/4341bb221ba12bf2ec2acde465370e1e76e909a9 Contains all the automatic ruff fixes = result of running pre-commit with previous commits (no further manual code changes)
* https://github.com/Consensys/mythril/commit/c08037316e98a10d7335c630736e9f810bcd58a1 Contains the manual fixes to the remaining lint findings ... (this commit requires careful review)
* ~~https://github.com/Consensys/mythril/commit/8b2d3f68ac9915293220eac8a35ecf1b65f85639 sorts the content of the requirements.txt by adding a pre-commit hook.~~ for later PR
* ~~https://github.com/Consensys/mythril/commit/5a758ae47b4224a9cce19952cccffe102ed27e42 reduces the requirements.txt to only contain runtime dependencies = removes all dependencies, that are either not directly imported or are not a transitive dependency (dependency of a dependency). Test dependencies are anyways defined in [setup.py](https://github.com/Consensys/mythril/blob/develop/setup.py#L56) and [tox.ini](https://github.com/Consensys/mythril/blob/develop/tox.ini#L5)   ... this all got possible by previous steps = finding and removing unused code via ruff.~~ for later PR

Why ruff and not flake8/pylint/ ...?: Ruff is 1. super fast, 2. adopted by more and more projects 3. has a `--fix` mode, so does not only find things 4. has many rulesets that can be activated with a unified configuration (implements all of flake8 + flake8-extensions, pylint, bandit, isort, black, pyupgrade, ...)

Why am I doing this: One of the next potential steps would be adding a `.pre-commit-hooks.yaml` file that allows running mythril as hook in other projects... this will benefit from having the dependencies already reduced to the minimum.

### CODE REVIEW

**Comment by dbast** [comment]
seems to require activation of Github Actions in the `Actions` tab of the repo (=free for OSS projects).

A successful pre-commit run can be seen in my repo fork https://github.com/dbast/mythril/actions/runs/10267898660/job/28409567561?pr=6

**Comment by norhh** [comment]
Better to separate https://github.com/Consensys/mythril/commit/8b2d3f68ac9915293220eac8a35ecf1b65f85639 into a new commit, as it is possible that the cross platform build may possibly fail.

**Comment by dbast** [comment]
@norhh removed https://github.com/Consensys/mythril/commit/8b2d3f68ac9915293220eac8a35ecf1b65f85639 + https://github.com/Consensys/mythril/commit/5a758ae47b4224a9cce19952cccffe102ed27e42 from this PR and added https://github.com/Consensys/mythril/pull/1865/commits/9147ee761ee1fec7cfeb29f91042998e8c896c0e according to your comment.

**Comment by dbast** [comment]
Should the pre-commit Github workflow be converted to be a circleci task instead?

**Review by norhh — APPROVED** [review]
Thank you for your contribution! :100:

**Pull request merged**
