### PR TITLE
Update cli.py

### PR DESCRIPTION
**Pull request by anonymousdouble**
refactor with chain assignment to make code more Pythonic, concise and efficient.

### CODE REVIEW

**Comment by norhh** [comment]
Hi @anonymousdouble,
Thanks for the contribution!
This doesn't fit the required formatting, so, can you run this following command to reformat the code in the local directory:
`python3 -m black .`

If you need help, I can do it for you!

**Comment by anonymousdouble** [comment]
Hi, thank you! Hope you can do it for me at your convenience. 
I attempted the command, but, unfortunately, the output is "All done, 223 files left unchanged.". It seems nothing has been changed, so I cannot commit it. Since it is about reformatting the code, I manually remove a blank line, but the checking is still not successful.
Screen Shot 2023-12-22 at 7 48 20 pm

**Comment by norhh** [comment]
Can you start a PR on develop rather than master? 
Create a branch from develop to make this PR

**Comment by norhh** [comment]
Better to actually create a fresh branch from develop and add the changes from this PR into it, as this patch was branched off from master, so it's not possible to merge it into develop, as you can see the failing tests and branch conflicts

**Comment by anonymousdouble** [comment]
Thank you, got it.  I just created a fresh branch from develop and added the changes from this PR into it. The new pull request is #1828. A little confused about the failing tests.

**Pull request closed without merging**
